apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: cinemaabyss
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      name: client
    - port: 9093
      name: controller
  selector:
    app: kafka
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: cinemaabyss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: cinemaabyss
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:4.0.1-rc2
        ports:
          - containerPort: 9092
            name: client
          - containerPort: 9093
            name: controller
        env:
          # Роли (и брокер, и контроллер в одном поде)
          - name: KAFKA_CFG_PROCESS_ROLES
            value: "broker,controller"

          # Уникальный ID для брокера
          - name: KAFKA_CFG_NODE_ID
            value: "1"

          # Настройки кворума контроллеров
          - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
            value: "1@kafka-0.kafka-headless.cinemaabyss.svc.cluster.local:9093"

          # Листенеры
          - name: KAFKA_CFG_LISTENERS
            value: "PLAINTEXT://:9092,CONTROLLER://:9093"

          # Адрес для клиентов внутри кластера
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-0.kafka-headless.cinemaabyss.svc.cluster.local:9092"

          # Указываем какой listener использовать для связи брокеров
          - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
            value: "PLAINTEXT"

          # Директория для хранения логов
          - name: KAFKA_CFG_LOG_DIRS
            value: "/bitnami/kafka/data"

        volumeMounts:
          - name: kafka-data
            mountPath: /bitnami/kafka/data

        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 20
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 20
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
