apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZbWxuWW05dmJUWTBPbWRvY0Y5ck56VlpaRFJUVTFGTWRubDBURmg0YnpkMVdXUXpVblZrVEdjMWJtd3dkbWxPTkdRPSIKICAgIH0KICB9Cn0K
type: kubernetes.io/dockerconfigjson