apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: YmlnYm9vbTY0OmdocF9RMElNTE5FQmtWbHRyY2FYek00NnlUMk5FWXppd1IybXg5SWE=
type: kubernetes.io/dockerconfigjson