name: Docker Build and Push

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/docker-build-push.yml'
  workflow_dispatch:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch build)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # =============================
      # Monolith
      # =============================
      - name: Build and push Monolith image
        uses: docker/build-push-action@v5
        with:
          context: ./src/monolith
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/monolith:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/monolith:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # =============================
      # Movies Service
      # =============================
      - name: Build and push Movies Service image
        uses: docker/build-push-action@v5
        with:
          context: ./src/microservices/movies
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/movies-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/movies-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # =============================
      # Events Service
      # =============================
      - name: Build and push Events Service image
        uses: docker/build-push-action@v5
        with:
          context: ./src/microservices/events
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/events-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/events-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # =============================
      # Proxy Service
      # =============================
      - name: Build and push Proxy Service image
        uses: docker/build-push-action@v5
        with:
          context: ./src/microservices/proxy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/proxy-service:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/proxy-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
